spring:
  datasource:
    name: taco-world
    url: jdbc:mysql://localhost:3306/taco-world-db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: MertMert96
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
logging:
  level:
    tacos: WARN
