spring:
  application:
    name: taco-world
  datasource:
    generate-unique-name: false
    name: taco-world
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 974228714506971
            client-secret: 4b02f459f5cb6bd3f7ad24f615b608fd
            scope: email, public_profile