spring:

  profiles:
    active: dev
  application:
    name: taco-world
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 974228714506971
            client-secret: 4b02f459f5cb6bd3f7ad24f615b608fd
            scope: email, public_profile
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
  jms:
    template:
      default-destination: order.queue
logging:
#  file:
#    path: /var/logs/
#    name: TacoWorld.log
  level:
    tacos: WARN

taco:
  orders:
    page-size: 10